version: '3.3'

services:
  db:
    build: 
      dockerfile: ./Dockerfile
    image: mysql:stable
    platform: linux/x86_64
    container_name: test_db
    #restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: taishi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
    ports:
      - "33066:3306"
    volumes:
      #- ./mysql:/var/lib/mysql
      - ./sql_code:/tmp
    expose:
      - 3306
